.PHONY: datatype contianer operator controlflow function

datatype:
	go run ./datatype/main.go

container:
	go run ./container/main.go

operator:
	go run ./operator/main.go

controlflow:
	go run ./controlflow/main.go

function:
	go run ./function/main.go