.PHONY: \
	datatype \ 
	array linked collecter map \
	if for \
	operator \
	controlflow \
	function \
	closures \
	pointer \
	time \

datatype:
	go	run ./datatype/main.go

operator:
	go run ./operator/main.go

function:
	go run ./Function/main.go

#Container
array:
	go run ./Container/Array/main.go

linked:
	go run ./Container/Linked/main.go

collecter:
	go run ./Container/Collecter/main.go

map:
	go run ./Container/Map/main.go
#########################################################

pointer:
	go run ./Pointer/main.go

# Controlflow
if:
	go run ./Controlflow/If/main.go

for:
	go run ./Controlflow/For/main.go
#########################################################

closures:
	go run ./Closures/main.go

# Time
time:
	go run ./Time/main.go
#########################################################