.PHONY: datatype contianer operator controlflow function closures pointer time

datatype:
	go run ./datatype/main.go

container:
	go run ./container/main.go

operator:
	go run ./operator/main.go

controlflow:
	go run ./controlflow/main.go

function:
	go run ./Function/main.go

closures:
	go run ./Closures/main.go

pointer:
	go run ./Pointer/main.go

time:
	go run ./Time/main.go